--- #YAML:1.0
name:               IPC-Mmap
version:            0.21
abstract:           minimal unified mmap for POSIX and Win32
author:
    - Dean Arnold, Presicient Corp. (darnold@presicient.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
